# Generated by Django 5.1.6 on 2025-02-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_author_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birth_year',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
