# Generated by Django 5.1.6 on 2025-02-25 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_book_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
    ]
