# Generated by Django 5.1.6 on 2025-03-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
